def get_word():
    import random as rd
    x = ["Abandon","Against","Anatomy","Ancient",
"Balance","Bandage","Capture",
"Comfort","Defense","Economy",
"Examine","Failure","Foreman",
"General","Harmony","Husband",
"Inquire","Justice","Library",
"Measure","Nominee","Organic",
"Protect","Quickly","Routine",
"Silence","Teacher","Venture",
"Welcome","Zeppelin","Absolve",
"Article","Blanket","Comfort",
"Diamond","Elastic","Freedom",
"Gallery","Husband","Inhale",
"Journey","Kitchen","Lacking",
"Mystery","Outside","Primary",
"Quicken","Reverse","Sanction",
"Teacher","Upgrade","Visible",
"Whistle","Abandon","Balance",
"Capture","Dispute","Eternal",
"Foresee","Gateway","Harmony",
"Intrude","Justice","Library",
"Maintain","Nothing","Overjoy",
"Plaster","Quicker","Recycle",
"Silence","Turning","Victory",
"Weather","Xenon","Youths","Zephyr",
"Assault","Bargain","Chalice",
"Delight","Engrave","Foreman",
"Grumble","Hostile","Inquire",
"Journey","Kernels","Liberty",
"Mantles","Network","Overlap",
"Privacy","Quizzes","Release",
"Seaside","Trivial","Upright",
"Volumes","Weekend"]
    return rd.choice(x)
